"""Description of the change

Revision ID: 9cfabf1a96bb
Revises: 173aa8da933c
Create Date: 2025-02-09 09:09:59.106330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfabf1a96bb'
down_revision: Union[str, None] = '173aa8da933c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('severity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'severity')
    # ### end Alembic commands ###
