"""your_migration_message

Revision ID: ed0aff52a4a5
Revises: 8f61acc72dc8
Create Date: 2025-02-09 00:02:46.232805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0aff52a4a5'
down_revision: Union[str, None] = '8f61acc72dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('schedules', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('schedules', 'created_at')
    # ### end Alembic commands ###
